name: ROS2 CI

on:
  pull_request:
    branches:
      - 'ros2'
  push:
    branches:
      - 'ros2'

jobs:
  test_environment:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
          - jazzy
          - kilted
          - rolling
        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: ghcr.io/sloretz/ros:humble-ros-base
            ros_version: 2
          # Jazzy Jalisco (May 2024 - May 2029)
          - docker_image: ghcr.io/sloretz/ros:jazzy-ros-base
            ros_distribution: jazzy
            ros_version: 2
          # Kilted Kaiju (May 2025 - December 2026)
          - docker_image: ghcr.io/sloretz/ros:kilted-ros-base
            ros_distribution: kilted
            ros_version: 2
          # Rolling Ridley  (June 2020 - Present)
          - docker_image: ghcr.io/sloretz/ros:rolling-ros-base 
            ros_distribution: rolling
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v6
        with:
          path: ros_ws/src
      - name: build and test
        uses: ros-tooling/action-ros-ci@master
        with:
          package-name: gscam
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
          coverage-result: false
